package org.hisp.dhis.importexport.mapping;

/*
 * Copyright (c) 2004-2007, University of Oslo
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 * * Neither the name of the HISP project nor the names of its contributors may
 *   be used to endorse or promote products derived from this software without
 *   specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

import java.util.Map;

import org.hisp.dhis.period.Period;

/**
 * This component is responsible for generating a mapping between the identifier
 * of an object prior to import and the identifier being auto-generated by the 
 * persistence medium during import. Setting the preview argument to true implies 
 * that no mapping takes place; simply returning the identifier prior to import.
 * 
 * @author Lars Helge Overland
 * @version $Id: ObjectMappingGenerator.java 5727 2008-09-18 17:48:54Z larshelg $
 */
public interface ObjectMappingGenerator
{
    String ID = ObjectMappingGenerator.class.getName();
    
    Map<Object, Integer> getCategoryMapping( boolean preview );
    
    Map<Object, Integer> getCategoryComboMapping( boolean preview );
    
    Map<Object, Integer> getCategoryOptionMapping( boolean preview );

    Map<Object, Integer> getCategoryOptionComboMapping( boolean preview );
        
    Map<Object, Integer> getDataElementMapping( boolean preview );
    
    Map<Object, Integer> getDataElementGroupMapping( boolean preview );
    
    Map<Object, Integer> getIndicatorMapping( boolean preview );

    Map<Object, Integer> getIndicatorGroupMapping( boolean preview );
    
    Map<Object, Integer> getIndicatorTypeMapping( boolean preview );
    
    Map<Object, Integer> getDataDictionaryMapping( boolean preview );
    
    Map<Object, Integer> getDataSetMapping( boolean preview );
    
    Map<Object, Integer> getOrganisationUnitMapping( boolean preview );

    Map<Object, Integer> getOrganisationUnitGroupMapping( boolean preview );
    
    Map<Object, Integer> getOrganisationUnitGroupSetMapping( boolean preview );
    
    Map<Object, Integer> getReportTableMapping( boolean preview );

    Map<Object, Integer> getPeriodMapping( boolean preview );
    
    Map<Period, Integer> getOnChangePeriodMapping( boolean preview );
    
    Map<String, Integer> getPeriodTypeMapping();
}
